name: geospatial_visualizer

channels:
  - conda-forge
  - bokeh

dependencies:
  - python
  - ipywidgets_bokeh
  - panel
  - geoviews
  - rioxarray
  - spatialpandas
  - geopandas
  - pandas
  - cartopy
  - holoviews
  - jupyterlab
  - requests
  - jupyter-panel-proxy
  - pip
  - pip:
    - sciencebasepy